### ISSUE TITLE
Website is not rendering

### ISSUE THREAD

**Issue by rcqx** [AlphaNtihinduka/Conference-capstone1#3]
Hiya Alpha, I noticed when checking the live version of your capstone project that it was not rendering properly (at least on my computer). Maybe you are refactoring it I don't know, but  just in case wanted to let you know ( :

![image](https://user-images.githubusercontent.com/58822719/167308111-775f6779-af4f-4034-a08b-4422515ffc67.png)

**Comment by AlphaNtihinduka** [comment]
Thank you so much @jr-cast , I have realized that I didn't create a new page after merging the branch. I have corrected the error. Thank you so much for the observation.

**Comment by rcqx** [comment]
Awesome!, you're welcome @AlphaNtihinduka, see you soon my friend 👍🏼
